# Generated by Django 5.0.9 on 2024-11-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(default=0, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
