# Generated by Django 5.0.9 on 2024-10-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short description for internal reference', max_length=100)),
                ('image', models.ImageField(help_text='Upload the banner image', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='URL to navigate to when banner is clicked', null=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to hide the banner')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of display, lower numbers show first')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
