# Generated by Django 5.0.9 on 2024-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='products/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
